project:
  type: website
  output-dir: _site
  preview:
    port: 4200
    browser: true

page-layout: full
execute:
  freeze: auto
  cache: true
  echo: true
  warning: true
  message: false
  error: true # errors will not stop rendering!

website:
  page-navigation: true
  back-to-top-navigation: true
  bread-crumbs: true
  open-graph: true
  search: true
  twitter-card: true
  title: "TRIZ: A Creative Problem-Solving System"
  site-url: "https://teaching-triz.netlify.app"
  repo-url: https://github.com/arvindvenkatadri/teachingtriz
  description: This is the teaching website of Arvind V., External Faculty, Srishti Manipal Institute of Art, Design, and Technology, Bangalore, India.
  favicon: "content/materials/icon-park-twotone--concept-sharing.svg"
  google-analytics: "" 
  reader-mode: true
  
  navbar:
    background: primary
    # foreground: "#FAF1B0"
    pinned: false
    collapse: true
    collapse-below: lg
    # left: 
    #   - text: "Home"
    #     file: index.qmd
      
    right:
      - icon: github
        href: https://github.com/arvindvenkatadri/teachingtriz
      - icon: twitter
        href: https://twitter.com/arvind_v
      - icon: linkedin
        href: https://www.linkedin.com/in/arvindvenkatadri
      - icon: envelope
        href: mailto:arvind.venkatadri@gmail.com

  sidebar:
    style: "docked"
    background: secondary
    alignment: left
    collapse-level: 2
    search: true
    logo: "content/materials/images/1book25.jpg"
    contents:
    
      - section: "Teaching"
        href: content/listing.qmd
        contents:
          - section: "Basic Ideas in Creativity"
            href: content/Basics/listing.qmd
            contents: 
              - content/Basics/Modules/10-Flow-and-Play/index.qmd
              - content/Basics/Modules/20-Cultural-Capital/index.qmd
              - content/Basics/Modules/30-MBTI-Big-5/index.qmd
              - content/Basics/Modules/40-Domain-Field-Self/index.qmd
              - content/Basics/Modules/50-Thinking-Fast-Slow/index.qmd
              - content/Basics/Modules/60-Parallel-Thinking/index.qmd
              - content/Basics/Modules/70-Metaphoric-Thinking/index.qmd
      
      
          - section: "TRIZ for Problem Solvers"
            href: content/TRIZ/listing.qmd
            contents: 
              - content/TRIZ/Modules/60-Problems-and-Contradictions/index.qmd
              - content/TRIZ/Modules/70-TRIZ-Resources/index.qmd
              - content/TRIZ/Modules/75-TRIZ-Ideal-Final-Result/index.qmd
              - content/TRIZ/Modules/80-A-Contradictory-Language/index.qmd
              - content/TRIZ/Modules/90-TRIZ-Contradiction-Matrix/index.qmd
              - content/TRIZ/Modules/95-TRIZ-Stories/index.qmd
              - content/TRIZ/Modules/100-TRIZ-Laws-of-Evolution/index.qmd
              - content/TRIZ/Modules/200-TRIZ-Advanced-Stuff/index.qmd
              - content/TRIZ/Modules/400-TRIZ-References/index.qmd
              - content/TRIZ/Modules/1000-TRIZ-Games/index.qmd 
              - content/TRIZ/Modules/7777-WritingAssignments/index.qmd 
        
      - section: "Case Studies and Talks"
        href: content/projects/listing.qmd      
        contents: 
          - content/projects/Modules/TRIZ/10-Lawrence-of-Arabia/index.qmd
          - content/projects/Modules/TRIZ/20-Spotify/index.en.qmd 
          - content/projects/Modules/TRIZ/30-Wildlife-Crossing/index.qmd  
          - content/projects/Modules/TRIZ/40-Owind/index.qmd
          - content/projects/Modules/TRIZ/50-BubbleBarrier/index.qmd
          - content/projects/Modules/Talks/TRIZTalkMay2025/index.qmd
              
  page-footer:
    center: "Website made with ❤️ and [Quarto](https://quarto.org/), by Arvind V."
    right:  Hosted by Netlify [{{< iconify simple-icons netlify >}}](https://www.netlify.com).
    left:  "License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)"
    background: light
    #   - icon: github
    #     href: https://github.com/arvindvenkatadri/
    #   - icon: twitter
    #     href: https://twitter.com/arvind_v
    #   - icon: envelope
    #     href: mailto:arvind.venkatadri@gmail.com
      # - icon: rss
      #   href: blog.xml
      #   
format:
  html:
    smooth-scroll: true
    fontsize: "medium"
    theme: united
    # css:
    #   - css/fira.css
    #   - css/roboto-condensed.css
    #   - css/vollkorn.css
    #   - css/playfair-display.css
    #   - css/chubbo.css
    #   - css/alegreya.css
    #   - css/montserrat.css
    #   - css/fraunces.css
    #   - css/styles.css
    # mainfont: Roboto Condensed
    # monofont: Fira Code
    link-external-icon: true
    link-external-newwindow: true
    citations-hover: true
    footnotes-hover: true
    page-navigation: true
    back-to-top-navigation: true
    bread-crumbs: true
    code-tools: false
    code-copy: true
    code-block-border-left: "black"
    code-block-bg: "#E7FBFE"
    code-fold: false
    code-summary: "Show the Code"
    code-overflow: scroll
    code-line-numbers: false # not with code-link:true
    code-link: true
    code-annotations: true
    format-links: true
    highlight-style: tango
    reference-location: document
    cap-location: bottom
    df-print: paged
    toc: true
    fig-align: center
    fig-cap-location: bottom
    # fig-asp: 0.618
    # fig-width: 5
    # fig-height: 4
    fig-dpi: 300

    filters:
      - d2
      - tabby
      - webr
      - quarto
      - line-highlight
      - shinylive
      - gadenbuie/tachyons # Causes strange code wrapping with decimals!

    d2:
      format: svg
      embed_mode: raw
    webr:
      channel-type: "automatic"
    mermaid:
      theme: forest

    grid:
      sidebar-width: 250px
      body-width: 1000px
      margin-width: 250px
      gutter-width: 1.5rem

  
editor: 
  source:
    markdown: 
      wrap: 72
lightbox: # Based on internal Quarto feature
  match: auto
  effect: zoom
  desc-position: right
  loop: false
  
# twitter-card:
#   creator: "@arvind_v"
#   card-style: summary_large_image
knitr:
  opts_chunk: 
    tidy: 'styler'
    


